version: "2"
services:
   dbserver:
      build: ./db-service
      image: jmguru/watcher_dbserver:latest
      environment:
        MYSQL_HOME: /var/lib/mysql
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: foodbase
      ports:
       - "3306:3306"
   appserver:
      build: ./food-service
      image: jmguru/watcher_appserver:latest
      environment:
       - DBHOST=dbserver
      ports:
       - "2115:2115"
      depends_on:
       - dbserver
      links:
       - dbserver
